#ifndef __PROFILES
#define __PROFILES

//  BASIC
#define PROFILE_BASIC_STARTPOINT_TIME           120;
#define PROFILE_BASIC_BETAGLUCANASE_TIME        0;
#define PROFILE_BASIC_DEBRANCHING_TIME          0;
#define PROFILE_BASIC_PROTEOLYTIC_TIME          0;
#define PROFILE_BASIC_BETAAMYLASE_TIME          3600;
#define PROFILE_BASIC_ALPHAAMYLASE_TIME         1800;
#define PROFILE_BASIC_MASHOUT_TIME              300;
#define PROFILE_BASIC_RECIRCULATION_TIME        1200;
#define PROFILE_BASIC_SPARGE_TIME               1200;
#define PROFILE_BASIC_BOIL_TIME                 5400;
#define PROFILE_BASIC_COOLING_TIME              120;

#define PROFILE_BASIC_STARTPOINT_TEMPERATURE    30;
#define PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE 40;
#define PROFILE_BASIC_DEBRANCHING_TEMPERATURE   40;
#define PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE   50;
#define PROFILE_BASIC_BETAAMYLASE_TEMPERATURE   60;
#define PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE  70;
#define PROFILE_BASIC_MASHOUT_TEMPERATURE       80;
#define PROFILE_BASIC_RECIRCULATION_TEMPERATURE 80;
#define PROFILE_BASIC_SPARGE_TEMPERATURE        80;
#define PROFILE_BASIC_BOIL_TEMPERATURE          100;
#define PROFILE_BASIC_COOLING_TEMPERATURE       25;


// TRIGO
#define PROFILE_TRIGO_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_TRIGO_BETAGLUCANASE_TIME        PROFILE_BASIC_BETAGLUCANASE_TIME;
#define PROFILE_TRIGO_DEBRANCHING_TIME          PROFILE_BASIC_DEBRANCHING_TIME;
#define PROFILE_TRIGO_PROTEOLYTIC_TIME          PROFILE_BASIC_PROTEOLYTIC_TIME;
#define PROFILE_TRIGO_BETAAMYLASE_TIME          PROFILE_BASIC_BETAAMYLASE_TIME;
#define PROFILE_TRIGO_ALPHAAMYLASE_TIME         PROFILE_BASIC_ALPHAAMYLASE_TIME;
#define PROFILE_TRIGO_MASHOUT_TIME              PROFILE_BASIC_MASHOUT_TIME;
#define PROFILE_TRIGO_RECIRCULATION_TIME        PROFILE_BASIC_RECIRCULATION_TIME;
#define PROFILE_TRIGO_SPARGE_TIME               PROFILE_BASIC_SPARGE_TIME;
#define PROFILE_TRIGO_BOIL_TIME                 PROFILE_BASIC_BOIL_TIME;
#define PROFILE_TRIGO_COOLING_TIME              PROFILE_BASIC_COOLING_TIME;

#define PROFILE_TRIGO_STARTPOINT_TEMPERATURE    45;
#define PROFILE_TRIGO_BETAGLUCANASE_TEMPERATURE PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE;
#define PROFILE_TRIGO_DEBRANCHING_TEMPERATURE   PROFILE_BASIC_DEBRANCHING_TEMPERATURE;
#define PROFILE_TRIGO_PROTEOLYTIC_TEMPERATURE   PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE;
#define PROFILE_TRIGO_BETAAMYLASE_TEMPERATURE   62;
#define PROFILE_TRIGO_ALPHAAMYLASE_TEMPERATURE  PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE;
#define PROFILE_TRIGO_MASHOUT_TEMPERATURE       78;
#define PROFILE_TRIGO_RECIRCULATION_TEMPERATURE PROFILE_BASIC_RECIRCULATION_TEMPERATURE;
#define PROFILE_TRIGO_SPARGE_TEMPERATURE        PROFILE_BASIC_SPARGE_TEMPERATURE;
#define PROFILE_TRIGO_BOIL_TEMPERATURE          PROFILE_BASIC_BOIL_TEMPERATURE;
#define PROFILE_TRIGO_COOLING_TEMPERATURE       PROFILE_BASIC_COOLING_TEMPERATURE;


// IPA
#define PROFILE_IPA_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_IPA_BETAGLUCANASE_TIME        PROFILE_BASIC_BETAGLUCANASE_TIME;
#define PROFILE_IPA_DEBRANCHING_TIME          PROFILE_BASIC_DEBRANCHING_TIME;
#define PROFILE_IPA_PROTEOLYTIC_TIME          PROFILE_BASIC_PROTEOLYTIC_TIME;
#define PROFILE_IPA_BETAAMYLASE_TIME          PROFILE_BASIC_BETAAMYLASE_TIME;
#define PROFILE_IPA_ALPHAAMYLASE_TIME         PROFILE_BASIC_ALPHAAMYLASE_TIME;
#define PROFILE_IPA_MASHOUT_TIME              PROFILE_BASIC_MASHOUT_TIME;
#define PROFILE_IPA_RECIRCULATION_TIME        PROFILE_BASIC_RECIRCULATION_TIME;
#define PROFILE_IPA_SPARGE_TIME               PROFILE_BASIC_SPARGE_TIME;
#define PROFILE_IPA_BOIL_TIME                 3900;
#define PROFILE_IPA_COOLING_TIME              PROFILE_BASIC_COOLING_TIME;

#define PROFILE_IPA_STARTPOINT_TEMPERATURE    PROFILE_TRIGO_STARTPOINT_TEMPERATURE;
#define PROFILE_IPA_BETAGLUCANASE_TEMPERATURE PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE;
#define PROFILE_IPA_DEBRANCHING_TEMPERATURE   PROFILE_BASIC_DEBRANCHING_TEMPERATURE;
#define PROFILE_IPA_PROTEOLYTIC_TEMPERATURE   PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE;
#define PROFILE_IPA_BETAAMYLASE_TEMPERATURE   PROFILE_TRIGO_BETAAMYLASE_TEMPERATURE;
#define PROFILE_IPA_ALPHAAMYLASE_TEMPERATURE  PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE;
#define PROFILE_IPA_MASHOUT_TEMPERATURE       PROFILE_TRIGO_MASHOUT_TEMPERATURE;
#define PROFILE_IPA_RECIRCULATION_TEMPERATURE PROFILE_BASIC_RECIRCULATION_TEMPERATURE;
#define PROFILE_IPA_SPARGE_TEMPERATURE        PROFILE_BASIC_SPARGE_TEMPERATURE;
#define PROFILE_IPA_BOIL_TEMPERATURE          PROFILE_BASIC_BOIL_TEMPERATURE;
#define PROFILE_IPA_COOLING_TEMPERATURE       PROFILE_BASIC_COOLING_TEMPERATURE;


// BELGA
#define PROFILE_BELGA_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_BELGA_BETAGLUCANASE_TIME        PROFILE_BASIC_BETAGLUCANASE_TIME;
#define PROFILE_BELGA_DEBRANCHING_TIME          PROFILE_BASIC_DEBRANCHING_TIME;
#define PROFILE_BELGA_PROTEOLYTIC_TIME          PROFILE_BASIC_PROTEOLYTIC_TIME;
#define PROFILE_BELGA_BETAAMYLASE_TIME          PROFILE_BASIC_BETAAMYLASE_TIME;
#define PROFILE_BELGA_ALPHAAMYLASE_TIME         PROFILE_BASIC_ALPHAAMYLASE_TIME;
#define PROFILE_BELGA_MASHOUT_TIME              PROFILE_BASIC_MASHOUT_TIME;
#define PROFILE_BELGA_RECIRCULATION_TIME        PROFILE_BASIC_RECIRCULATION_TIME;
#define PROFILE_BELGA_SPARGE_TIME               PROFILE_BASIC_SPARGE_TIME;
#define PROFILE_BELGA_BOIL_TIME                 PROFILE_BASIC_BOIL_TIME;
#define PROFILE_BELGA_COOLING_TIME              PROFILE_BASIC_COOLING_TIME;

#define PROFILE_BELGA_STARTPOINT_TEMPERATURE    PROFILE_TRIGO_STARTPOINT_TEMPERATURE;
#define PROFILE_BELGA_BETAGLUCANASE_TEMPERATURE PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE;
#define PROFILE_BELGA_DEBRANCHING_TEMPERATURE   PROFILE_BASIC_DEBRANCHING_TEMPERATURE;
#define PROFILE_BELGA_PROTEOLYTIC_TEMPERATURE   PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE;
#define PROFILE_BELGA_BETAAMYLASE_TEMPERATURE   PROFILE_TRIGO_BETAAMYLASE_TEMPERATURE;
#define PROFILE_BELGA_ALPHAAMYLASE_TEMPERATURE  PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE;
#define PROFILE_BELGA_MASHOUT_TEMPERATURE       PROFILE_TRIGO_MASHOUT_TEMPERATURE;
#define PROFILE_BELGA_RECIRCULATION_TEMPERATURE PROFILE_BASIC_RECIRCULATION_TEMPERATURE;
#define PROFILE_BELGA_SPARGE_TEMPERATURE        PROFILE_BASIC_SPARGE_TEMPERATURE;
#define PROFILE_BELGA_BOIL_TEMPERATURE          PROFILE_BASIC_BOIL_TEMPERATURE;
#define PROFILE_BELGA_COOLING_TEMPERATURE       PROFILE_BASIC_COOLING_TEMPERATURE;


// RED
#define PROFILE_RED_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_RED_BETAGLUCANASE_TIME        PROFILE_BASIC_BETAGLUCANASE_TIME;
#define PROFILE_RED_DEBRANCHING_TIME          PROFILE_BASIC_DEBRANCHING_TIME;
#define PROFILE_RED_PROTEOLYTIC_TIME          PROFILE_BASIC_PROTEOLYTIC_TIME;
#define PROFILE_RED_BETAAMYLASE_TIME          PROFILE_BASIC_BETAAMYLASE_TIME;
#define PROFILE_RED_ALPHAAMYLASE_TIME         PROFILE_BASIC_ALPHAAMYLASE_TIME;
#define PROFILE_RED_MASHOUT_TIME              PROFILE_BASIC_MASHOUT_TIME;
#define PROFILE_RED_RECIRCULATION_TIME        PROFILE_BASIC_RECIRCULATION_TIME;
#define PROFILE_RED_SPARGE_TIME               PROFILE_BASIC_SPARGE_TIME;
#define PROFILE_RED_BOIL_TIME                 PROFILE_BASIC_BOIL_TIME;
#define PROFILE_RED_COOLING_TIME              PROFILE_BASIC_COOLING_TIME;

#define PROFILE_RED_STARTPOINT_TEMPERATURE    PROFILE_TRIGO_STARTPOINT_TEMPERATURE;
#define PROFILE_RED_BETAGLUCANASE_TEMPERATURE PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE;
#define PROFILE_RED_DEBRANCHING_TEMPERATURE   PROFILE_BASIC_DEBRANCHING_TEMPERATURE;
#define PROFILE_RED_PROTEOLYTIC_TEMPERATURE   PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE;
#define PROFILE_RED_BETAAMYLASE_TEMPERATURE   PROFILE_TRIGO_BETAAMYLASE_TEMPERATURE;
#define PROFILE_RED_ALPHAAMYLASE_TEMPERATURE  PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE;
#define PROFILE_RED_MASHOUT_TEMPERATURE       PROFILE_TRIGO_MASHOUT_TEMPERATURE;
#define PROFILE_RED_RECIRCULATION_TEMPERATURE PROFILE_BASIC_RECIRCULATION_TEMPERATURE;
#define PROFILE_RED_SPARGE_TEMPERATURE        PROFILE_BASIC_SPARGE_TEMPERATURE;
#define PROFILE_RED_BOIL_TEMPERATURE          PROFILE_BASIC_BOIL_TEMPERATURE;
#define PROFILE_RED_COOLING_TEMPERATURE       PROFILE_BASIC_COOLING_TEMPERATURE;


// APA
#define PROFILE_APA_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_APA_BETAGLUCANASE_TIME        PROFILE_BASIC_BETAGLUCANASE_TIME;
#define PROFILE_APA_DEBRANCHING_TIME          PROFILE_BASIC_DEBRANCHING_TIME;
#define PROFILE_APA_PROTEOLYTIC_TIME          PROFILE_BASIC_PROTEOLYTIC_TIME;
#define PROFILE_APA_BETAAMYLASE_TIME          PROFILE_BASIC_BETAAMYLASE_TIME;
#define PROFILE_APA_ALPHAAMYLASE_TIME         PROFILE_BASIC_ALPHAAMYLASE_TIME;
#define PROFILE_APA_MASHOUT_TIME              PROFILE_BASIC_MASHOUT_TIME;
#define PROFILE_APA_RECIRCULATION_TIME        PROFILE_BASIC_RECIRCULATION_TIME;
#define PROFILE_APA_SPARGE_TIME               PROFILE_BASIC_SPARGE_TIME;
#define PROFILE_APA_BOIL_TIME                 PROFILE_BASIC_BOIL_TIME;
#define PROFILE_APA_COOLING_TIME              PROFILE_BASIC_COOLING_TIME;

#define PROFILE_APA_STARTPOINT_TEMPERATURE    PROFILE_TRIGO_STARTPOINT_TEMPERATURE;
#define PROFILE_APA_BETAGLUCANASE_TEMPERATURE PROFILE_BASIC_BETAGLUCANASE_TEMPERATURE;
#define PROFILE_APA_DEBRANCHING_TEMPERATURE   PROFILE_BASIC_DEBRANCHING_TEMPERATURE;
#define PROFILE_APA_PROTEOLYTIC_TEMPERATURE   PROFILE_BASIC_PROTEOLYTIC_TEMPERATURE;
#define PROFILE_APA_BETAAMYLASE_TEMPERATURE   PROFILE_TRIGO_BETAAMYLASE_TEMPERATURE;
#define PROFILE_APA_ALPHAAMYLASE_TEMPERATURE  PROFILE_BASIC_ALPHAAMYLASE_TEMPERATURE;
#define PROFILE_APA_MASHOUT_TEMPERATURE       PROFILE_TRIGO_MASHOUT_TEMPERATURE;
#define PROFILE_APA_RECIRCULATION_TEMPERATURE PROFILE_BASIC_RECIRCULATION_TEMPERATURE;
#define PROFILE_APA_SPARGE_TEMPERATURE        PROFILE_BASIC_SPARGE_TEMPERATURE;
#define PROFILE_APA_BOIL_TEMPERATURE          PROFILE_BASIC_BOIL_TEMPERATURE;
#define PROFILE_APA_COOLING_TEMPERATURE       PROFILE_BASIC_COOLING_TEMPERATURE;


// CUSTOM
#define PROFILE_CUSTOM_STARTPOINT_TIME           PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_BETAGLUCANASE_TIME        PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_DEBRANCHING_TIME          PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_PROTEOLYTIC_TIME          PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_BETAAMYLASE_TIME          PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_ALPHAAMYLASE_TIME         PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_MASHOUT_TIME              PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_RECIRCULATION_TIME        PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_SPARGE_TIME               PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_BOIL_TIME                 PROFILE_BASIC_STARTPOINT_TIME;
#define PROFILE_CUSTOM_COOLING_TIME              PROFILE_BASIC_STARTPOINT_TIME;

#define PROFILE_CUSTOM_STARTPOINT_TEMPERATURE    30;
#define PROFILE_CUSTOM_BETAGLUCANASE_TEMPERATURE 45;
#define PROFILE_CUSTOM_DEBRANCHING_TEMPERATURE   50;
#define PROFILE_CUSTOM_PROTEOLYTIC_TEMPERATURE   55;
#define PROFILE_CUSTOM_BETAAMYLASE_TEMPERATURE   65;
#define PROFILE_CUSTOM_ALPHAAMYLASE_TEMPERATURE  75;
#define PROFILE_CUSTOM_MASHOUT_TEMPERATURE       70;
#define PROFILE_CUSTOM_RECIRCULATION_TEMPERATURE 85;
#define PROFILE_CUSTOM_SPARGE_TEMPERATURE        90;
#define PROFILE_CUSTOM_BOIL_TEMPERATURE          95;
#define PROFILE_CUSTOM_COOLING_TEMPERATURE       100;

#endif //__PROFILES
